### ISSUE TITLE
clang bug is due to wrong invocation, not a bug!

### ISSUE THREAD

**Issue by Jannik2099** [KOLANICH-libs/Hardening.cmake#1]
Your supposed "clang bug" happens because you are not passing -pie to the linker driver (clang), but only the linker. 

The linker driver is responsible for selecting the appropriate startup files, and since it sees no -pie it assumes non-pie startup files. Passing -pie to the linker driver will also forward it to the linker.

There's two reasons you may not have encountered  this with gcc:
1. gcc defaults to pie on most distributions.
2. GNU ld may be configured to allow textrels by default

**Comment by KOLANICH** [comment]
Thank you for your explaination. I have fixed the script and have rewritten this repo (my other repos using this script as a submodule are not yet upgraded, it'd take some time).

Sorry for the delay, I was offline for some time.

I have tested it locally, now works for me. Please check if it works for you, and close the issue in this case.
